variables:
  # Init submodules.
  # See https://docs.gitlab.com/ee/ci/yaml/#git-submodule-strategy
  GIT_SUBMODULE_STRATEGY: "recursive"

  # Use shallow cloning to speed up git clone. This can fail, if retrying an older build on CI
  # and the old commit is not in the shallow history any more.
  # See https://docs.gitlab.com/ee/ci/yaml/#shallow-cloning
  GIT_DEPTH: "50"

  # run make paralel
  MAKEFLAGS: "-j10"

  # pipenv cache
  PIPENV_VENV_IN_PROJECT: "true"
  PIPENV_CACHE_DIR: ".cache/"

stages:
  - environment
  - prebuild
  - build
  - test

cache:
  paths:
    - .cache/
    - .venv/

before_script:
  - pipenv install

include:
  - ci/environment.yml
  - ci/prebuild.yml  # common, style
  - ci/core.yml
  - ci/legacy.yml
  # - ci/python.yml  TODO
  - ci/crypto.yml
  - ci/storage.yml
